admin-part/src/test-integration/kotlin/e2e/BuildMethodsTests.kt, admin-part/src/test-integration/kotlin/e2e/CoverageByPackagesTest.kt, admin-part/src/test-integration/kotlin/e2e/CoverageTest.kt, admin-part/src/test-integration/kotlin/e2e/PluginInstanceStateTest.kt, admin-part/src/test-integration/kotlin/e2e/RisksTest.kt, admin-part/src/test-integration/kotlin/e2e/ScopeTest.kt, admin-part/src/test-integration/kotlin/e2e/SessionTest.kt
Added a new test for state checking.
Expanded e2e CoverageByPackageTest.
Added BuildMethodsTests.
Fixed issues when assertions don't work when we get null for .apply{}.
=> EPMDJ-1836. Part of new tests and improvements.

admin-part/src/main/kotlin/Coverage.kt, admin-part/src/main/kotlin/Summary.kt, api/src/commonMain/kotlin/Model.kt
changed the calculation of average coverage: count instructions instead of methods
=> EPMDJ-2411 Service Group - Aggregated Coverage

admin-part/src/main/kotlin/AgentData.kt, admin-part/src/main/kotlin/BuildHandler.kt, admin-part/src/main/kotlin/Plugin.kt, admin-part/src/main/kotlin/State.kt, api/src/commonMain/kotlin/Actions.kt, api/src/commonMain/kotlin/Model.kt, api/src/jvmMain/kotlin/Routes.kt, tests/src/test/kotlin/e2e/PluginInstanceStateTest.kt
stored 'baseline' in DB; init first build as baseline; added action for updating current build as baseline
=> EPMDJ-5136 Add an action for Baseline

admin-part/src/main/kotlin/Build.kt, api/src/commonMain/kotlin/Model.kt
=> EPMDJ-5033 "New Build" pop-up displaying after restarting the Admin

admin-part/src/main/kotlin/AgentData.kt, admin-part/src/main/kotlin/Build.kt, admin-part/src/main/kotlin/Plugin.kt, admin-part/src/main/kotlin/State.kt, admin-part/src/test/kotlin/AgentStateTest.kt, build.gradle.kts, tests/src/test/kotlin/Channels.kt, tests/src/test/kotlin/Extensions.kt, tests/src/test/kotlin/Stream.kt
add parentVersion for Baseline and CachedBuild
=> EPMDJ-5136 Baseline. Fixed the cases when redeploy a build

admin-part/src/main/kotlin/State.kt, admin-part/src/test/kotlin/AgentStateTest.kt, admin-part/src/test/kotlin/PluginTest.kt
=> EPMDJ-5459 Baseline. cases when redeploy a stored build

admin-part/src/main/kotlin/Build.kt, admin-part/src/main/kotlin/BuildTests.kt, admin-part/src/main/kotlin/Plugin.kt, admin-part/src/main/kotlin/State.kt, admin-part/src/main/kotlin/TestsToRun.kt, admin-part/src/main/kotlin/coverage/Model.kt, admin-part/src/main/kotlin/group/Summary.kt, admin-part/src/main/kotlin/storage/Build.kt, admin-part/src/test/kotlin/PluginTest.kt, api/src/commonMain/kotlin/Model.kt, api/src/jvmMain/kotlin/Routes.kt
added TestsToRunDuration of a build to db;
=> EPMDJ-5544 Add a topic for bar charts

admin-part/src/main/kotlin/Plugin.kt, admin-part/src/main/kotlin/Scope.kt, admin-part/src/main/kotlin/ScopeHandler.kt, api/src/jvmMain/kotlin/Routes.kt, tests/src/test/kotlin/Stream.kt
moved scope topics to build context
=> EPMDJ-5750 Change API for scopes

admin-part/src/main/kotlin/Scope.kt, admin-part/src/main/kotlin/ScopeHandler.kt, admin-part/src/main/kotlin/State.kt, admin-part/src/main/kotlin/storage/Scope.kt, admin-part/src/main/kotlin/storage/Session.kt, admin-part/src/test/kotlin/PluginTest.kt
take sessions for a scope from DB instead of storing them when switch scope
=> EPMDJ-6307 Out of memory when finish session or scope

admin-part/src/main/kotlin/Plugin.kt, admin-part/src/main/kotlin/storage/Build.kt, admin-part/src/test/kotlin/AgentStateTest.kt, api/src/commonMain/kotlin/Actions.kt, api/src/commonMain/kotlin/Model.kt
=> EPMDJ-6966 [BE] Investigation - how to work with old builds

api/src/commonMain/kotlin/Model.kt
refactoring: remove unused JvmSerializable
=> EPMDJ-6919 configuration of FST serialization

admin-part/src/main/kotlin/CoverageTree.kt, admin-part/src/main/kotlin/coverage/Calc.kt, admin-part/src/main/kotlin/coverage/Ext.kt, admin-part/src/main/kotlin/coverage/Model.kt, admin-part/src/test/kotlin/JsCoverageTest.kt, admin-part/src/test/kotlin/test/js/Data.kt, api/src/commonMain/kotlin/Model.kt
added to topic boolProbes for Classes; fixed probeRange for Methods
=> EPMDJ-7841 Return info of probes for JS agent

admin-part/src/main/kotlin/Plugin.kt, admin-part/src/main/kotlin/State.kt, admin-part/src/test/kotlin/PluginTest.kt
removed the recalculation of scopes and other unnecessary updates
=> EPMDJ-7736 Improve performance when restart Admin

admin-part/src/main/kotlin/jvm/JacocoExt.kt, agent-part/src/main/kotlin/Plugin.kt
=> EPMDJ-7274 Filter interfaces when it instruments classes

admin-part/src/main/kotlin/AgentData.kt, admin-part/src/main/kotlin/Coverage.kt, admin-part/src/main/kotlin/Plugin.kt, admin-part/src/main/kotlin/ScopeHandler.kt, admin-part/src/main/kotlin/State.kt, admin-part/src/main/kotlin/util/PerfLogger.kt, admin-part/src/test/kotlin/AgentStateTest.kt, admin-part/src/test/kotlin/JsCoverageTest.kt, admin-part/src/test/kotlin/PluginTest.kt, gradle.properties
=> EPMDJ-8578 Store class bytes by a new key (agentId and buildVersion)

admin-part/src/main/kotlin/BuildTests.kt, admin-part/src/main/kotlin/Coverage.kt, admin-part/src/main/kotlin/Plugin.kt, api/src/commonMain/kotlin/Model.kt
also rename TestName properties
=> EPMDJ-8941 Made TestName as mandatory parameter for TestDetails

.github/workflows/check.yml, .github/workflows/publish.yml
load test report if check is failed
=> EPMDJ-9178 Extend test output for github actions

admin-part/src/main/kotlin/storage/Scope.kt, gradle.properties
=> EPMDJ-9218 Open tasks and refactoring

admin-part/src/main/kotlin/QualityGate.kt, admin-part/src/main/kotlin/storage/Build.kt, admin-part/src/main/kotlin/storage/Scope.kt, admin-part/src/test/kotlin/util/PostgresBased.kt, gradle.properties
=> EPMDJ-9213 get schema from TransactionManagement or connection

README.md, admin-part/src/main/kotlin/Actions.kt, admin-part/src/main/kotlin/Plugin.kt, admin-part/src/main/kotlin/Scope.kt, admin-part/src/main/kotlin/ScopeHandler.kt, admin-part/src/test/kotlin/perf/PerformanceTest.kt, agent-api/src/commonMain/kotlin/Actions.kt, agent-api/src/commonMain/kotlin/Messages.kt, agent-api/src/commonMain/kotlin/Model.kt, agent-part/src/main/kotlin/Plugin.kt, api/src/commonMain/kotlin/Actions.kt, plugin-runner/build.gradle.kts, tests/src/test/kotlin/e2e/RisksTest.kt, tests/src/test/kotlin/e2e/ScopeTest.kt
remove action SCOPE_INITIALIZED; init scope by admin part instead of agent
=> EPMDJ-9811 Finish scope when agent is offline

admin-part/src/main/kotlin/Plugin.kt
use actual context instead of old
=> EPMDJ-10448 Incorrect recalculation of Tests2Run
